<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="tf_prefix" value=""/>
    <xacro:property name="base_length" value="0.23"/> <!-- Largo del chasis [m]-->
    <xacro:property name="base_width" value="0.15"/>  <!-- Ancho del chasis [m]-->
    <xacro:property name="base_height" value="0.075"/> <!-- Altura del chasis [m]-->
    <xacro:property name="wheel_radius" value="0.04"/> <!-- Radio de ruedas [m]-->
    <xacro:property name="wheel_length" value="0.03"/> <!-- Grosor de ruedas [m]-->
    <xacro:property name="caster_radius" value="0.009525"/>

    <link name="${tf_prefix}base_footprint"/>

    <!-- CHASIS PRINCIPAL -->
    <!--base_link
        Qué es Chasis principal del robot
        Ubicación Centro geométrico del chasis
    -->
    <link name="${tf_prefix}base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="1.6" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
         xyz="0 0 ${2*base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name ="grey"/>
            </visual>
            <xacro:cylinder_inertia m="0.5" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="${tf_prefix}left"/>
    <xacro:wheel_link prefix="${tf_prefix}right"/>

    <!-- RUEDA LOCA -->
    <link name="${tf_prefix}caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <xacro:sphere_inertia m="0.2" r="${2*caster_radius}" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
    </link>

    <!-- IMU Link -->
    <link name="${tf_prefix}imu_link">
        <visual>
            <geometry>
                <box size="0.02 0.015 0.007"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
        </visual>
    </link>

    <!--sensor ultrasonico-->
    <link name = "${tf_prefix}range_link">
        <visual>
            <geometry>
                <box size = "0.018 0.045 0.025"/>
            </geometry>
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
    </link>
    
    <!--base_footprint
        Qué es Punto de contacto con el suelo (origen del robot)
        Ubicación Justo debajo del chasis, a altura de las ruedas
    -->
    <joint name="${tf_prefix}base_joint" type="fixed">
        <parent link="${tf_prefix}base_footprint"/>
        <child link="${tf_prefix}base_link"/>
        <origin xyz="0 0 0.01" rpy="0 0 0"/> <!--${wheel_radius}-->
    </joint>

    
    <joint name="${tf_prefix}base_right_wheel_joint" type="continuous">
        <parent link="${tf_prefix}base_link"/>
        <child link="${tf_prefix}right_wheel_link"/>
        <origin xyz="-0.023 -0.09 0.03" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="4.5" effort="2.5"/>
    </joint>

    <joint name="${tf_prefix}base_left_wheel_joint" type="continuous">
        <parent link="${tf_prefix}base_link"/>
        <child link="${tf_prefix}left_wheel_link"/>
        <origin xyz="-0.023 0.09 0.03" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="4.5" effort="2.5"/> 
    </joint> <!--Velocidad angular máxima en radianes/segundo Par torsional máximo en Newton-metros (Nm) -->

    <joint name="${tf_prefix}base_caster_wheel_joint" type="fixed">
        <parent link="${tf_prefix}base_link"/>
        <child link="${tf_prefix}caster_wheel_link"/>
        <origin xyz="0.09 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Joint between base_link and imu_link -->
    <joint name="${tf_prefix}imu_joint" type="fixed">
        <parent link="${tf_prefix}base_link"/>
        <child link="${tf_prefix}imu_link"/>
        <origin xyz="-0.06 -0.0675 ${base_height + 0.0035}" rpy="0 0 0"/>
    </joint>

    <!-- Joint between base_link and imu_link -->
    <joint name="${tf_prefix}range_joint" type="fixed">
        <parent link="${tf_prefix}base_link"/>
        <child link="${tf_prefix}range_link"/>
        <origin xyz="${base_length/2} 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    
</robot>